### ISSUE TITLE
Use same Page Navigation list on multiple pages across site

### ISSUE THREAD

**Issue by addmitt** [bschlintz/spfx-pagenavigation#1]
I guess this is more of a feature request. We've been desperate for a better navigation system in Sharepoint sites and were hoping this web part would do the trick, but it seems a unique Page Navigation list is generated for every page on the site. So if we want to use this as a Knowledgebase/Help/Documentation-style navigation for dozens of pages, we'd have to recreate the same list on every page (and edit every single page whenever there is a change).

If there were an option when adding the Page Navigation web part to point it at an existing list, instead of creating a unique one for every page, I feel like this would instantly be capable for use as a more global-style navigation. If made possible, support for multiple Page Navigation web parts would be nice as well, to allow for say, a global navigation list in a left column, and a page-level navigation list in a right column.

Perhaps there's already a way of accomplishing this that I am not finding, but just in case there isn't, figured I'd bring this up here.

**Comment by bschlintz** [comment]
It has been quite awhile since I’ve looked at this code, but I believe this creates one list per site with each page on that site getting it’s own item in that list. It does not currently support sharing the list across sites though.

**Comment by addmitt** [comment]
Right, yeah. And I'm not looking to use a single Navigation list across multiple sites, rather, just use one configured Navigation list (and by that I suppose I mean one of the configured rows in the List created for the site) on multiple pages on the same site.

The left-hand navigation of SharePoint sites is just so awful (text is large, no word wrap on entries, cannot embed very deep or resize width, etc etc) and we're looking for an alternative heh.

**Comment by addmitt** [comment]
My jank solution: modified PageNavService.ts to set the same this._serverRelativePageUrl all the time:

`this._serverRelativePageUrl = 'singlenav';`

Though I do still like the idea of supporting more than one of these per page, but I understand this wasn't the original intention/design of this project. Feel free to close this Issue if you've no plans to make any changes to this repo.
